
<!doctype html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>
            
                Digitální akademie Czechitas - přípravka Pythonu: Výjimky
            
        </title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

        

        <link rel="stylesheet" href="/static/css/naucse.css">
        <link rel="stylesheet" href="/static/css/body.css">
        <link rel="stylesheet" href="/static/css/pygments-lovelace-style.css">
        <link rel="stylesheet" href="/static/css/ipython.css">

        
    <link rel="canonical" href="https://naucse.python.cz/lessons/beginners/exceptions/" />


        <style>
            
    

        </style>
    </head>

    <body>
        <nav class="header">
            <ul class="container menu">
                <li><a href="/" class="logo"><h1>Nauč se Python!</h1></a></li>
                <li><a href="/courses/" class="menu-link"><h2>Materiály</h2></a></li>
                <li><a href="/runs/" class="menu-link"><h2>Kurzy</h2></a></li>
            </ul>
        </nav>

        

<div class="page">
    <div class="container">

        
            <header class="lesson-header">
                <a href="/">Nauč se Python </a>
                
                > <a href="/runs/">Kurzy</a>
                
                

> <a href="/2018/czechitas-ostrava-jaro/">Digitální akademie Czechitas - přípravka Pythonu</a>

> <a href="/2018/czechitas-ostrava-jaro/sessions/modules/">Moduly a výjimky</a>

> <a href="/2018/czechitas-ostrava-jaro/beginners/exceptions/">Výjimky</a>


                <hr>
            </header>
        

        
  


        <div class="lesson-content">
          
    

    <h1>Výjimky</h1>
<p>Pojďme si prohloubit znalosti o chybách, neboli odborně o <em>výjimkách</em>
(angl. <em>exceptions</em>).</p>
<p>Vezmi následující funkci:</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">nacti_cislo</span><span class="p">():</span>
    <span class="n">odpoved</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s1">'Zadej číslo: '</span><span class="p">)</span>
    <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="n">odpoved</span><span class="p">)</span>
</pre></div><p>Když uživatel nezadá číslice, ale třeba text <code>cokolada</code>,
nastane výjimka jménem <code>ValueError</code> (chyba hodnoty) a Python vypíše
odpovídající chybovou hlášku.</p>
<div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">"ukazka.py"</span>, line <span class="m">3</span>, in <span class="n">nacti_cislo</span>
    <span class="n">cislo</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="n">odpoved</span><span class="p">)</span>
<span class="gr">ValueError</span>: <span class="n">invalid literal for int() with base 10: 'cokolada'</span>
</pre></div><p>Program volá funkci <code>int()</code> pro něco, co nedává smysl jako číslo.
Co s tím má chudák funkce <code>int</code> dělat?
Není žádná rozumná hodnota, kterou by mohla vrátit.
Převádění tohoto textu na celé číslo nedává smysl.</p>
<p>Až funkce <code>nacti_cislo</code> nejlíp „ví“, co se má stát, když uživatel nezadá
číslice.
Stačí se uživatele zeptat znovu!
Kdybys měla funkci, která zjistí jestli jsou v řetězci jen číslice,
mohlo by to fungovat nějak takhle:</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">nacti_cislo</span><span class="p">():</span>
    <span class="k">while</span> <span class="kc">True</span><span class="p">:</span>
        <span class="n">odpoved</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s1">'Zadej číslo: '</span><span class="p">)</span>
        <span class="k">if</span> <span class="n">obsahuje_jen_cislice</span><span class="p">(</span><span class="n">odpoved</span><span class="p">):</span>
            <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="n">odpoved</span><span class="p">)</span>  <span class="c1"># máme výsledek, funkce končí</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="nb">print</span><span class="p">(</span><span class="s1">'To nebylo číslo!'</span><span class="p">)</span>
            <span class="c1"># ... a zeptáme se znovu -- cyklus `while` pokračuje</span>
</pre></div><p>Kde ale vzít funkci <code>obsahuje_jen_cislice</code>?
Nemá smysl ji psát znovu – funkce <code>int</code> sama nejlíp pozná, co se dá převést na
číslo a co ne.
A dokonce nám to dá vědět – chybou, kterou můžeš <em>zachytit</em>.</p>
<div class="admonition note"><p>Ono „obsahuje_jen_cislice“ v Pythonu existuje. Dokonce několikrát.
Místo řešení problému to ale spíš ilustruje, v čem problém spočívá:</p>
<ul>
<li>Řetězcová metoda <code>isnumeric</code> vrací <code>True</code> pokud řetězec obsahuje číslice:
<code>'123'.isnumeric()</code> je pravda; <code>'abc'.isnumeric()</code> nepravda.
Problém je, že funkci <code>int</code> potřebuje jeden konkrétní druh číslic:
pro řetězce jako <code>'½'</code> nebo <code>'௩三๓໓</code>' (trojka v tamilském, japonském,
thajském nebo laoském písmu) platí <code>isnumeric</code>, ale <code>int</code> si na nich
vyláme zuby stejně jako na <code>'abc'</code>.</li>
<li>Řetězcová metoda <code>isdecimal</code> vrací <code>True</code> pokud řetězec obsahuje arabské
číslice 0-9. To už je lepší, ale stejně to úplně nesedí: <code>int</code> si poradí
s mezerou na začátku, např. s <code>' 3'</code>, ale funkce <code>isdecimal</code> takový řetězec
odmítne.</li>
</ul>
<p>Chceš-li zjistit jestli funkce <code>int</code> umí daný řetězec převést na číslo,
nejlepší je použít přímo funkci <code>int</code>.</p>
</div><h2>Ošetření chyby</h2>
<p>Pro zachycení chyby má Python příkaz <code>try</code>/<code>except</code>.</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">nacti_cislo</span><span class="p">():</span>
    <span class="k">while</span> <span class="kc">True</span><span class="p">:</span>
        <span class="n">odpoved</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s1">'Zadej číslo: '</span><span class="p">)</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="n">odpoved</span><span class="p">)</span>
        <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
            <span class="nb">print</span><span class="p">(</span><span class="s1">'To nebylo číslo!'</span><span class="p">)</span>
</pre></div><p>Jak to funguje?
Příkazy v bloku uvozeném příkazem <code>try</code> se normálně provádějí, ale když
nastane uvedená výjimka, Python přeskočí zbytek bloku <code>try</code> a provede všechno 
v bloku <code>except</code>.
Pokud výjimka nenastala, přeskočí se celý blok <code>except</code>.</p>
<h2>Druhy chyb</h2>
<p>A co je to <code>ValueError</code>? To je typ chyby.
Podobných typů je spousta.
Všechny jsou popsané <a href="https://docs.python.org/3/library/exceptions.html#exception-hierarchy">v dokumentaci</a>; pro nás jsou (nebo budou) důležité tyto:</p>
<div class="highlight"><pre><code>BaseException
 ├── SystemExit                     vyvolána funkcí exit()
 ├── KeyboardInterrupt              vyvolána po stisknutí Ctrl+C
 ╰── Exception
      ├── ArithmeticError
      │    ╰── ZeroDivisionError    dělení nulou
      ├── AssertionError            nepovedený příkaz `assert`
      ├── AttributeError            neexistující atribut/metoda, např. 'abc'.len
      ├── ImportError               nepovedený import
      ├── LookupError
      │    ╰── IndexError           neexistující index, např. 'abc'[999]
      ├── NameError                 použití neexistujícího jména proměnné
      │    ╰── UnboundLocalError    použití proměnné, která ještě nebyla nastavená
      ├── SyntaxError               špatná syntaxe, program je nečitelný/nepoužitelný
      │    ╰── IndentationError     špatné odsazení
      │         ╰── TabError        kombinování mezer a tabulátorů v odsazení
      ├── TypeError                 špatný typ, např. len(9)
      ╰── ValueError                špatná hodnota, např. int('xyz')</code></pre></div><p>Tohle si není potřeba pamatovat – druh chyby, kterou je potřeba zachytit,
vždy najdeš v příslušné chybové hlášce.</p>
<p>Když odchytáváš obecnou výjimku,
chytnou se i všechny podřízené typy výjimek –
například <code>except ArithmeticError:</code> zachytí i <code>ZeroDivisionError</code>.
A <code>except Exception:</code> zachytí <em>všechny</em> výjimky, které běžně chceš zachytit.</p>
<h2>Nechytej je všechny!</h2>
<p>Většinu chyb <em>není</em> potřeba ošetřovat.</p>
<p>Nastane-li <em>nečekaná</em> situace, je téměř vždy
mnohem lepší program ukončit, než se snažit
pokračovat dál a počítat se špatnými hodnotami.
Navíc chybový výstup, který Python standardně
připraví, může hodně ulehčit hledání chyby.</p>
<p>Zachytávej tedy jenom ty chyby, které <em>očekáváš</em> – víš přesně, která chyba může
nastat a proč; máš možnost správně zareagovat.</p>
<p>V našem příkladu to platí pro <code>ValueError</code> z funkce <code>int</code>: víš že uživatel
nemusí vždy zadat číslo ve správném formátu a víš že správná
reakce na tuhle situaci je problém vysvětlit a zeptat se znovu.</p>
<p>Co ale dělat, kdyš uživatel chce ukončit program a zmáčkne
<kbd>Ctrl</kbd>+<kbd>C</kbd>?
Nebo když se mu porouchá klávesnice a selže funkce <code>input</code>?
Nejlepší reakce na takovou nečekanou situaci ukončit program a informovat
uživatele (nebo lépe, programátora), že (a kde) je něco špatně.
Neboli vypsat chybovou hlášku.
A to se stane normálně, bez <code>try</code>.</p>
<h2>Další přílohy k <code>try</code></h2>
<p>Pro úplnost: kromě <code>except</code> existují dva jiné bloky,
které můžeš „přilepit“ k <code>try</code>, a to <code>else</code> a <code>finally</code>.
První se provede, když v <code>try</code> bloku
žádná chyba nenastane; druhý se provede vždy – ať
už chyba nastala nebo ne.</p>
<p>Můžeš taky použít více bloků <code>except</code>. Provede se vždy maximálně jeden:
ten první, který danou chybu umí ošetřit.</p>
<div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">neco_udelej</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">'Tohle se provede, pokud nastane ValueError'</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">NameError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">'Tohle se provede, pokud nastane NameError'</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">'Tohle se provede, pokud nastane jiná chyba'</span><span class="p">)</span>
    <span class="c1"># (kromě SystemExit a KeyboardInterrupt, ty chytat nechceme)</span>
<span class="k">except</span> <span class="ne">TypeError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">'Tohle se neprovede nikdy'</span><span class="p">)</span>
    <span class="c1"># ("except Exception" výše ošetřuje i TypeError; sem se Python nedostane)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">'Tohle se provede, pokud chyba nenastane'</span><span class="p">)</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">'Tohle se provede vždycky; i pokud v `try` bloku byl např. `return`'</span><span class="p">)</span>
</pre></div><h2>Vyvolání chyby</h2>
<p>Občas se stane, že výjimku budeš potřebovat vyvolat sama.</p>
<p>Často se to stává když píšeš nějakou obecnou funkci.
Třeba funkci na výpočet obsahu čtverce.
Co se stane, když někdo zavolá <code>obsah_ctverce(-5)</code>?</p>
<ul>
<li>Zadal-li ono <code>-5</code> uživatel, je potřeba mu vynadat a zeptat se znovu.</li>
<li>Naměřil-li <code>-5</code> nějaký robotický aparát, je potřeba ho líp zkalibrovat.</li>
<li>Vyšel-li čtverec se stranou <code>-5</code> v nějakém výpočtu, je nejspíš potřeba opravit
chybu v tom výpočtu.</li>
</ul>
<p>Samotná funkce <code>obsah_ctverce</code> ale „neví“, proč ji někdo volá.
Jejím úkolem je jen něco spočítat.
Měla by být použitelná ve všech případech výše – a v mnoha dalších.</p>
<p>Když někdo zavolá <code>obsah_ctverce(-5)</code>, <em>neexistuje</em> správný výsledek, který by
funkce mohla vrátit.
Místo vrácení výsledku musí tato funkce <em>signalizovat chybu</em>.
S tou se pak může program, který <code>obsah_ctverce(-5)</code> zavolal,
vypořádat – vynadat uživateli, zkalibrovat měřák, nebo, pokud na chybu není
připravený, sám skončit s chybou (a upozornit tak programátora, že je něco
špatně).</p>
<p>Jak na to prakticky?
Chybu můžeš vyvolat pomocí příkazu <code>raise</code>.
Za příkaz dáš druh výjimky a pak do závorek nějaký popis toho, co je špatně.</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">obsah_ctverce</span><span class="p">(</span><span class="n">strana</span><span class="p">):</span>
    <span class="k">if</span> <span class="n">strana</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">strana</span> <span class="o">**</span> <span class="mi">2</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="sa">f</span><span class="s1">'Strana musí být kladná, číslo </span><span class="si">{</span><span class="n">strana</span><span class="si">}</span><span class="s1"> kladné není!'</span><span class="p">)</span>
</pre></div><p>Podobně jako <code>return</code>, i příkaz <code>raise</code> ukončí funkci.
A nejen tu – pokud na tuhle konkrétní chybu není program předem připravený,
ukončí se celý program.</p>
<p>Ze začátku není u <code>raise</code> příliš důležité dumat nad tím, který typ výjimky je
ten správný.
Klidně „střílej od boku“.
<code>ValueError</code> bývá často správná volba.</p>


        </div>

        
        <hr class="lesson-end">

        
            <div class="alert alert-info">
                Toto je stránka lekce z kurzu, který probíhá nebo proběhl naživo s instruktorem.
                
                    
                        <a href="https://naucse.python.cz/lessons/beginners/exceptions/">Přejít na stejnou lekci v kurzu pro samouky</a>.
                    
                
            </div>
        


        
    <div class="row prev-next">
        
            
            
                
    <div class="col text-left">
        <a href="/2018/czechitas-ostrava-jaro/sessions/modules/">↑ <span class="d-none d-sm-inline">Lekce: Moduly a výjimky</span></a>
    </div>

            
            
                
    <div class="col text-right">
        <a href="/2018/czechitas-ostrava-jaro/beginners/modules/"><span class="d-none d-sm-inline">Moduly</span> →</a>
    </div>

            
        
    </div>


        

    </div>
</div>



        <script type="text/javascript" src="/static/js/solutions.js"></script>

        <div class="footer container">
            <hr>
            <div class="lesson-attribution">
                
                    <p>
                        Uprav tuto stránku na
                        <a href="https://github.com/pyvec/naucse.python.cz/blob/master/lessons/beginners/exceptions/index.md">
                            
                                <svg class="icon icon-github" viewBox="0 0 64 64">
<path d="M32 0 C14 0 0 14 0 32 0 53 19 62 22 62 24 62 24 61 24 60 L24 55 C17 57 14 53 13 50 13 50 13 49 11 47 10 46 6 44 10 44 13 44 15 48 15 48 18 52 22 51 24 50 24 48 26 46 26 46 18 45 12 42 12 31 12 27 13 24 15 22 15 22 13 18 15 13 15 13 20 13 24 17 27 15 37 15 40 17 44 13 49 13 49 13 51 20 49 22 49 22 51 24 52 27 52 31 52 42 45 45 38 46 39 47 40 49 40 52 L40 60 C40 61 40 62 42 62 45 62 64 53 64 32 64 14 50 0 32 0 Z" fill="currentColor" stroke-width="0"/>
</svg>
                            
                          GitHubu
                        </a>
                    </p>
                

                
    
        <p>Pro PyLadies Brno napsal Petr Viktorin, 2014-2017.</p>
    

                
    <p>
        Licence:
        <a href="https://creativecommons.org/licenses/by-sa/4.0/">
            Creative Commons Attribution-ShareAlike 4.0 International
        </a>
    </p>
    

                
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

        

    </body>
</html>